### ISSUE TITLE
Symbol not found: _mysql2_set_field_string_encoding

### ISSUE THREAD

**Issue by rubenfonseca** [brianmario/mysql2#216]
Hi. I'm trying ruby-1.9.3-preview1 on OS X 10.7.2, and when I try to use mysql2 on Rails 3.1.1, I have the following error:

```
dyld: lazy symbol binding failed: Symbol not found: _mysql2_set_field_string_encoding
  Referenced from: /Users/rubenfonseca/.rvm/gems/ruby-1.9.3-rc1/gems/mysql2-0.3.7/lib/mysql2/mysql2.bundle
  Expected in: flat namespace

dyld: Symbol not found: _mysql2_set_field_string_encoding
  Referenced from: /Users/rubenfonseca/.rvm/gems/ruby-1.9.3-rc1/gems/mysql2-0.3.7/lib/mysql2/mysql2.bundle
  Expected in: flat namespace
```

It works fine on any other ruby (ree, 1.9.2).

I can't find any information on the internets. Any hint? Thank you very much for your work!
