### ISSUE TITLE
Cannot install 0.4.7 on MySQL 5.1 (CentOS 6)

### ISSUE THREAD

**Issue by marutosi** [brianmario/mysql2#866]
```
$ rpm -qf /usr/include/mysql/mysql.h
mysql-devel-5.1.73-8.el6_8.x86_64
```

```
$ gem install mysql2 -v '0.4.7'
Building native extensions.  This could take a while...
ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    current directory: /home/xxxxx/.rvm/gems/ruby-2.3.4/gems/mysql2-0.4.7/ext/mysql2
/home/xxxxx/.rvm/rubies/ruby-2.3.4/bin/ruby -r ./siteconf20170702-31295-51dkj2.rb extconf.rb
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for rb_big_cmp()... yes
-----
Using mysql_config at /usr/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
checking for SSL_MODE_DISABLED in mysql.h... no
checking for MYSQL_OPT_SSL_ENFORCE in mysql.h... no
checking for MYSQL.net.vio in mysql.h... yes
checking for MYSQL.net.pvio in mysql.h... no
-----
Setting libpath to /usr/lib64/mysql
-----
creating Makefile

current directory: /home/xxxxx/.rvm/gems/ruby-2.3.4/gems/mysql2-0.4.7/ext/mysql2
make "DESTDIR=" clean

current directory: /home/xxxxx/.rvm/gems/ruby-2.3.4/gems/mysql2-0.4.7/ext/mysql2
make "DESTDIR="
compiling statement.c
compiling result.c
result.c: In function 'rb_mysql_result_alloc_result_buffers':
result.c:326: warning: assignment from incompatible pointer type
result.c:328: warning: assignment from incompatible pointer type
At top level:
cc1: warning: unrecognized command line option "-Wno-used-but-marked-unused"
cc1: warning: unrecognized command line option "-Wno-static-in-inline"
cc1: warning: unrecognized command line option "-Wno-reserved-id-macro"
cc1: warning: unrecognized command line option "-Wno-missing-variable-declarations"
cc1: warning: unrecognized command line option "-Wno-documentation-unknown-command"
cc1: warning: unrecognized command line option "-Wno-disabled-macro-expansion"
cc1: warning: unrecognized command line option "-Wno-covered-switch-default"
cc1: warning: unrecognized command line option "-Wno-conditional-uninitialized"
compiling mysql2_ext.c
compiling client.c
client.c: In function '_mysql_client_options':
client.c:906: error: 'MYSQL_ENABLE_CLEARTEXT_PLUGIN' undeclared (first use in this function)
client.c:906: error: (Each undeclared identifier is reported only once
client.c:906: error: for each function it appears in.)
client.c: In function 'set_enable_cleartext_plugin':
client.c:1329: error: 'MYSQL_ENABLE_CLEARTEXT_PLUGIN' undeclared (first use in this function)
At top level:
cc1: warning: unrecognized command line option "-Wno-used-but-marked-unused"
cc1: warning: unrecognized command line option "-Wno-static-in-inline"
cc1: warning: unrecognized command line option "-Wno-reserved-id-macro"
cc1: warning: unrecognized command line option "-Wno-missing-variable-declarations"
cc1: warning: unrecognized command line option "-Wno-documentation-unknown-command"
cc1: warning: unrecognized command line option "-Wno-disabled-macro-expansion"
cc1: warning: unrecognized command line option "-Wno-covered-switch-default"
cc1: warning: unrecognized command line option "-Wno-conditional-uninitialized"
make: *** [client.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/xxxxx/.rvm/gems/ruby-2.3.4/gems/mysql2-0.4.7 for inspection.
Results logged to /home/xxxxx/.rvm/gems/ruby-2.3.4/extensions/x86_64-linux/2.3.0/mysql2-0.4.7/gem_make.out
```

**Comment by marutosi** [comment]
This is caused by #845.
https://github.com/brianmario/mysql2/pull/845/files#diff-3b04aa8aa3de9a18e251b4a95981f3dfR889

**Comment by sodabrew** [comment]
Oh no! I forgot to provide a fallback case for earlier versions of MySQL. Thank you for reporting!

**Comment by ppoektos** [comment]
I have the same error.

**Comment by sodabrew** [comment]
Resolved by #867

**Comment by marutosi** [comment]
When 0.4.8 will be released?

**Comment by sodabrew** [comment]
My target date is Monday July 10. I want to give a few days to see if any other problem reports appear this week.

**Comment by seanmckinley** [comment]
@sodabrew you guys still planning on releasing 0.4.8 today?

**Comment by sodabrew** [comment]
Yes, on track for today!
