### ISSUE TITLE
segfault when using cache_rows true

### ISSUE THREAD

**Issue by SamSaffron** [brianmario/mysql2#691]
Noticing new segfaults when using cache_rows true

example here:

https://gist.github.com/dandv/9d260ba2bf1113fd0b4e

This used to work perfect feels like a recent regression.

**Comment by sodabrew** [comment]
Thanks for the bug report and backtrace. The key part of the trace seems to be:
```
-- C level backtrace information -------------------------------------------
ruby(+0x179c08) [0x556684e69c08]
ruby(+0x1e64aa) [0x556684ed64aa]
ruby(rb_bug+0xb3) [0x556684ed7743]
ruby(+0xf2cd4) [0x556684de2cd4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f4f078f3340]
/usr/lib/x86_64-linux-gnu/libmysqlclient.so.18(mysql_fetch_row+0x59) [0x7f4f05c6cb29]
ruby(+0x186141) [0x556684e76141]
/usr/local/lib/ruby/gems/2.0.0/gems/mysql2-0.4.1/lib/mysql2/mysql2.so(+0xa9db) [0x7f4f061799db] result.c:535
/usr/local/lib/ruby/gems/2.0.0/gems/mysql2-0.4.1/lib/mysql2/mysql2.so(+0xb8a6) [0x7f4f0617a8a6] result.c:824
```

Of course in the 0.4.x series this code has changed to accommodate the Prepared Statements code path, but the particular path you're on is the classic query execution.

**Comment by dandv** [comment]
I'm the end user who [ran into this bug while using a Discourse migration script](https://meta.discourse.org/t/core-dump-when-running-the-mybb-import-script/34332?u=dandv). Not a Ruby dev, so all I could help with was the trace.

Actually I see the crash with `cache_rows: false`. It occurs in [this script](https://github.com/discourse/discourse/blob/master/script/import_scripts/mybb.rb#L218), and setting `cache_rows: true` prevents the crash, but all but the last batches of records are discarded, and only the last batch is processed. (Again, I'm not a Ruby dev, so if there's something else wrong with the script, I wouldn't know.) Gem versions below.

```sh
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.10.6)
io-console (0.4.2)
json (1.7.7)
minitest (4.3.2)
mysql2 (0.4.1)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
rubygems-update (2.4.8)
test-unit (2.0.0.0)
```

**Comment by sodabrew** [comment]
You should downgrade to msyql2 0.3.x if you need this to work immediately. I'll see about fixing the issue in the 0.4.x branch as I have time.

**Comment by dandv** [comment]
The latest version that didn't crash with that importer script was 0.3.5. v0.3.6, 0.3.7, 0.3.10 and 0.3.20 caused the crash.

**Comment by sodabrew** [comment]
Just to clarify: this began crashing with 0.3.6, but worked fine with 0.3.5?

**Comment by dandv** [comment]
After further testing, what happens is that 0.3.5 doesn't crash because [this line](https://github.com/discourse/discourse/blob/master/script/import_scripts/mybb.rb#L49) in the script causes it to die with

> *** NoMethodError Exception: undefined method `size' for #<Mysql2::Result:0x...>

I see that [0.3.6 added `size`](https://github.com/brianmario/mysql2/releases/tag/0.3.6), which lets the script run past that line up to the point it crashes.

Here's [the trace](https://gist.github.com/dandv/ce1a3f47781f38af91a5) with mysql2 0.3.20. The only modifications I've made to [the script](https://github.com/discourse/discourse/blob/master/script/import_scripts/mybb.rb) were in the connection details.

This suggests MyBB imports (and [probably other forums](https://meta.discourse.org/t/core-dump-when-running-the-mybb-import-script/34332/3?u=dandv)) into Discourse are broken. I'm happy to help as much as I can, given my very limited Ruby knowledge. Hopefully @SamSaffron has some ideas on how to get this working until the issue is fixed in the 0.4.x branch.

**Comment by ajaska** [comment]
See #737

**Comment by sodabrew** [comment]
@ajaska But this bug occurs on the 0.3.x tree, which doesn't have prepa
red statement support.

**Comment by sodabrew** [comment]
Should be resolved by #745 (which will be backported to 0.3.x as well).
