### ISSUE TITLE
Mysql2 with Ruby on Rails 3.2.22

### ISSUE THREAD

**Issue by bjm88** [brianmario/mysql2#709]
Hi,
  I'm wondering what version of Mysql2 is required to work with mysql 5.6 (or 5.7 or AWS Aurora) and also Rails 3.2.x.  ?  When moving to AWS Aurora we also wanted to update our mysql client from 5.5 to 5.6 and update mysql2 from 0.3.10 to 0.4.2.  I found doing this I got the following errors...

Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (can't activate mysql2 (~> 0.3.10), already activated mysql2-0.4.2. Make sure all dependencies are added to Gemfile.)

so then installed activerecord-mysql2-adapter also....

I got it all to bundle install fine and startup.  The site is even up with no errors, but first interaction with the database has a weird error...

NoMethodError (undefined method `accept' for nil:NilClass):

 Rendered /Users/Ben/.rvm/gems/ruby-2.1.5@caredox/gems/actionpack-3.2.22/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.0ms)
  Rendered /Users/Ben/.rvm/gems/ruby-2.1.5@caredox/gems/actionpack-3.2.22/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.7ms)
  Rendered /Users/Ben/.rvm/gems/ruby-2.1.5@caredox/gems/actionpack-3.2.22/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (19.7ms)

Is this supported?

**Comment by sodabrew** [comment]
In your Gemfile, use `gem 'mysql2', '~> 0.3.10'` and let it jump to the highest available 0.3.x, without going to 0.4.x (which will be supported starting in Rails 4.2.5 soon, but not any earlier versions of Rails).

**Comment by bjm88** [comment]
Thank you, is that mentioned in Readme?  Also can it explain what versions of mysql server it supports connecting to....

**Comment by sodabrew** [comment]
I've just updated the README to include compatibility notes for mysql2 0.4.x: https://github.com/brianmario/mysql2#compatibility

**Comment by ShaggyDishu** [comment]
i just started working on a project it has `rails 3.2.22.5` and using `mysql2 gem version 0.3.11`,

i am getting the following error:

`NameError: uninitialized constant Mysql2::Client::LONG_PASSWORD`

how can i fix it?

**Comment by Faq** [comment]
Please open new issue
